language: python
python:
  - '3.6'
sudo: required
dist: trusty
before_install:
  - pwd
install:
  - pwd
  - cd /home/travis/build/hurwitzlab/agave-app-test
  - pip install -r requirements.txt
script:
  - travis_wait 30 pytest -s -n 4
  - pwd
  - ls -l
env:
  global:
    secure: dPLE2W9gM+7eU+mFJccQniC/9QxyVgGu1YiwYW7uLlBD9LcNY5iCCTcpjKUkl9nBO1qK0kjQaYFmIB+/TKtLGqdiXzZM2XKFNTW8RtonUtKQSJFeWZpZv3mY2pjCSl4X+qOGqmw4u9Lgk9VhTxH7S5aK9ta8cBxeFDGdadOsHOwgRlsCmjOEPj6EQWfw6fIeF0vfrGqTnpqmcDECICiyW+nqQpXoaYJ5a90QTc3/3Trke7OWf6OzuAmxBATCwpywdReNTBYXeh2d/5V/5yXUuMT1YBALCaLFqGGh5/87V9mpRF4X+OIS7vX9skTM9ktLB4+aCU3qT3v1Y4Aqy6hsRCdCVdUBBhtnqjkWOSoX2K2QKt2PHhyXW5hPobB73pA9KMoRW1+4tkZTbTNZF7pnsukRrUs1sQKVrFFBICUurCVnQ2qomM64u5Y7bHu997V5FjobEq4Oin3O5dkB9OwXR7ejjP4j+l3hNd142wPThFLzA4NmJKMuXSxiwXQQVSEdNzBiriFV+NiOeCjN9npl5iWXsmkI5reyXZ4RHNwjqeG/4w819AO2osjuvAnznJUz9bq/FDkilbEA+EDh4JuqIPEZH7lxrknoVAo/gUNwT7jZRTfJgbGVdcGvXqOTUNH1CC+HbeWBbWMopi17fDvAakoo3i1QJO4kLoaYndOiUxw=
notifications:
  slack:
    secure: iBZAcs/a5yuiViHX2A94tCDgNzhXeP+rF3s5sga1+SrUIO+LJUnz97SHN8Fa97k+xTqyjvQnav2KCKRZVuIyYsCeuoGN+GoKoOX4/hCLF8u82F068hladqjFgcqYmDRCvXmRPC+b9QJqgXxQ0/8PnCfTvoEfA6J41QnyFlDH4PXuGesY97hEZVWAx6CgKbebiMQfVAuSCAdmcmMXE1RhswTrmYAwTlKrMNFjjnfixQWls9oXmbrp7Svbdt2yujZwiWFiKQcdZ34yLQslwK5WjO5gScfjPQvijDsOaQKihg+aCv3bZBKg18FlUVlagPyeG7R+Ia+gKl1L9fMq/O7s+rxIhIJ3kK7wWoQMo3zPSbDvhiSGtKrfWIB3dvNozyZxg2hTdjkMxTD9KGUsZRHOUK9osUw7L32D9CyN4fCuj8tbAUTBLOpmPTrd4lQvvzxvA5sRK2BkLE4skVrvXfsDzz6BBHErA5mh6cpDgNuMjgq6f/J1glO/G8CpuC12OBGA8ETkHaDs58BDaIlVBhOjpust/g1CiuQ06gN3uI4002E446jLs6J9lWNBY7FLj1d6wythlOUEtEkWw3cEb/w9VVutYMIbVp+icaqPpnui/A6qnZRbgV0f2eYJQcjaVlnZxiK5DqZPx2nhrkcVrqy3q8nTTfir4T09EQEfIe4u/ts=
